### ISSUE TITLE
Docker compose failure

### ISSUE THREAD

**Issue by samuel-hxs** [FAForever/faf-stack#34]
Docker failes to compose 
Branch develop
docker-compose up -d faf-python-server

``````
Step 5/11 : RUN python3.5 -m pip install --trusted-host content.faforever.com -r /tmp/requirements.txt

 ---> Running in 8b0b413d3073

Looking in links: http://content.faforever.com/wheel/

Collecting requests (from -r /tmp/requirements.txt (line 1))

  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)

Collecting typing (from -r /tmp/requirements.txt (line 2))

  Downloading https://files.pythonhosted.org/packages/05/2b/2b05bf1d5a9dd450447c9a5df3e118a465e5d3cb12b73b7220a5064a403f/typing-3.6.4-py3-none-any.whl

Collecting aiohttp==1.3.3 (from -r /tmp/requirements.txt (line 4))

  Downloading https://files.pythonhosted.org/packages/64/6f/817da9651f73536ad6138427617742052e1f8614c3f968467c6ab629cc3f/aiohttp-1.3.3-cp35-cp35m-manylinux1_x86_64.whl (167kB)

Collecting aiomysql (from -r /tmp/requirements.txt (line 5))

  Downloading https://files.pythonhosted.org/packages/c3/de/0787b44efbdb31722c06522d8565dcb8fc9c3b017abf6484a52f2935f8b2/aiomysql-0.0.19-py3-none-any.whl

Collecting aiomeasures (from -r /tmp/requirements.txt (line 6))

  Downloading https://files.pythonhosted.org/packages/0f/aa/40f89fc915669b8492b5f060597aff25d9b11ad10f28fb4a97cba6896658/aiomeasures-0.5.14-py2.py3-none-any.whl

Collecting coveralls (from -r /tmp/requirements.txt (line 7))

  Downloading https://files.pythonhosted.org/packages/6f/c0/cd0b33454c0192cdd63360f8ac2a96a6132f01b34fa70524220c06fd4743/coveralls-1.3.0-py2.py3-none-any.whl

Collecting docopt (from -r /tmp/requirements.txt (line 8))

  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz

Collecting pycrypto (from -r /tmp/requirements.txt (line 9))

  Downloading https://files.pythonhosted.org/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz (446kB)

Collecting semver (from -r /tmp/requirements.txt (line 10))

  Downloading https://files.pythonhosted.org/packages/21/18/a0de8cda637ba3efee1b3617ded00601507ce15bd70a39399740e0fd415f/semver-2.8.1-py2.py3-none-any.whl

Collecting pygeoip (from -r /tmp/requirements.txt (line 11))

  Downloading https://files.pythonhosted.org/packages/f2/48/a3ce59694fa05605fee44273fe2d8b7e9df0d808cdf3914de1771b8986c4/pygeoip-0.3.2-py2.py3-none-any.whl

Collecting pytest==2.8.2 (from -r /tmp/requirements.txt (line 12))

  Downloading https://files.pythonhosted.org/packages/08/8b/d6225fbe08f4d5c1b4ff05d274596f76003064dfb3ac6aa483790d1bdd08/pytest-2.8.2-py2.py3-none-any.whl (149kB)

Collecting pytest-mock (from -r /tmp/requirements.txt (line 13))

  Downloading https://files.pythonhosted.org/packages/5e/58/c97f24442020f91af0a4a266280f48b2cbbc43b4e33b0955ac3b3425a5ff/pytest_mock-1.10.0-py2.py3-none-any.whl

Collecting pytest-cov (from -r /tmp/requirements.txt (line 14))

  Downloading https://files.pythonhosted.org/packages/30/7d/7f6a78ae44a1248ee28cc777586c18b28a1df903470e5d34a6e25712b8aa/pytest_cov-2.5.1-py2.py3-none-any.whl

Collecting pyflakes (from -r /tmp/requirements.txt (line 15))

  Downloading https://files.pythonhosted.org/packages/44/98/af7a72c9a543b1487d92813c648cb9b9adfbc96faef5455d60f4439aa99b/pyflakes-2.0.0-py2.py3-none-any.whl (53kB)

Collecting msgpack-python (from -r /tmp/requirements.txt (line 16))

  Downloading https://files.pythonhosted.org/packages/8a/20/6eca772d1a5830336f84aca1d8198e5a3f4715cd1c7fc36d3cc7f7185091/msgpack-python-0.5.6.tar.gz (138kB)

Collecting rsa (from -r /tmp/requirements.txt (line 17))

  Downloading https://files.pythonhosted.org/packages/e1/ae/baedc9cb175552e95f3395c43055a6a5e125ae4d48a1d7a924baca83e92e/rsa-3.4.2-py2.py3-none-any.whl (46kB)

Collecting trueskill (from -r /tmp/requirements.txt (line 18))

  Downloading https://files.pythonhosted.org/packages/49/01/8572ac20d2877037cb65711ee0b76a0bf7efc11b7f3354e4eae3072f51a1/trueskill-0.4.4.tar.gz

Collecting aiocron (from -r /tmp/requirements.txt (line 19))

  Downloading https://files.pythonhosted.org/packages/7d/c0/be621f7c3b603d8bfa09a57e0e7526a38f74ef4ccb5e27b0b7a14b402b6a/aiocron-1.2-py2.py3-none-any.whl

Collecting marisa-trie (from -r /tmp/requirements.txt (line 20))

  Downloading https://files.pythonhosted.org/packages/20/95/d23071d0992dabcb61c948fb118a90683193befc88c23e745b050a29e7db/marisa-trie-0.7.5.tar.gz (270kB)

Collecting oauth2client (from -r /tmp/requirements.txt (line 21))

  Downloading https://files.pythonhosted.org/packages/82/d8/3eab58811282ac7271a081ba5c0d4b875ce786ca68ce43e2a62ade32e9a8/oauth2client-4.1.2-py2.py3-none-any.whl (99kB)

Collecting faftools from git+https://github.com/FAForever/faftools.git@38fc8e10f3cbd50d3f6abe9168e9040c08ad26cf#egg=faftools (from -r /tmp/requirements.txt (line 22))

  Cloning https://github.com/FAForever/faftools.git (to revision 38fc8e10f3cbd50d3f6abe9168e9040c08ad26cf) to /tmp/pip-install-lft5wuco/faftools

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-install-lft5wuco/faftools/setup.py", line 4, in <module>

        from pip.req import parse_requirements

    ImportError: No module named 'pip.req'

    

    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-lft5wuco/faftools/

ERROR: Service 'faf-python-server' failed to build: The command '/bin/sh -c python3.5 -m pip install --trusted-host content.faforever.com -r /tmp/requirements.txt' returned a non-zero code: 1
``````
```

**Comment by Sheeo** [comment]
Moved to server repo
